# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-13 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='res_body',
            field=models.TextField(help_text='Response of the API'),
        ),
        migrations.AlterField(
            model_name='api',
            name='res_type',
            field=models.IntegerField(choices=[(500, 'JSON'), (600, 'HTML'), (700, 'TEXT')], db_index=True, help_text='Response type of the API'),
        ),
    ]
