# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-13 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20190113_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='path',
            field=models.CharField(help_text='The path for the api', max_length=256),
        ),
    ]
